# Generated by Django 2.2.4 on 2020-07-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keltrans_app', '0004_auto_20200718_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='packet',
            field=models.FileField(upload_to='contracts'),
        ),
    ]
