# Generated by Django 2.2.4 on 2020-07-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keltrans_app', '0005_auto_20200718_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='packet',
            field=models.FileField(blank=True, upload_to='contracts'),
        ),
    ]
