# Generated by Django 2.2.4 on 2020-07-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keltrans_app', '0006_auto_20200718_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='mc_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='packet',
            field=models.FileField(upload_to='contracts'),
        ),
    ]
