# Generated by Django 2.2.4 on 2020-07-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keltrans_app', '0008_auto_20200718_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='file1',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='file10',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='file2',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='file3',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='file4',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='file5',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='file6',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='file7',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='file8',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='file9',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
